name: Test

on:
  push:
    branches:
      - master
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: wrapper
    strategy:
      matrix:
        browser: ["firefox"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Rust
        uses: actions-rs/toolchain@v1
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tensorflow.js Converter
        run: pip install tensorflowjs
      - name: Download models
        run: ./download_models.sh
        working-directory: quality/models
      - uses: actions/setup-node@v1
      - name: Build module
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Lint
        run: npm run lint
        working-directory: ${{env.working-directory}}
      - name: Test Rust build
        run: cargo run --bin test_reference -- simple_onnx ../quality/tests/inputs.json ../quality/tests/outputs.json
        working-directory: ${{env.working-directory}}
      - name: Run Cypress tests
        uses: cypress-io/github-action@v1
        with:
          working-directory: ${{env.working-directory}}
          start: python -m http.server 8000 -d ..
          wait-on: 'http://localhost:8000'
          browser: ${{ matrix.browser }}
